name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11 (AGP 7.4 compatible)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-30
            build-tools;30.0.3
            ndk;22.1.7171670
            cmake;3.22.1

      - name: Build with Gradle (root)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.6'
          arguments: :app:assembleDebug --no-daemon --stacktrace

      - name: Upload APK artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-outputs
          path: |
            app/build/outputs/**