name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: write

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11 (AGP 7.4 compatible)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-30
            build-tools;30.0.3
            ndk;22.1.7171670
            cmake;3.22.1

      # بناء نسخة Debug دائماً
      - name: Build Debug
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.6'
          arguments: :app:assembleDebug --no-daemon --stacktrace

      - name: Upload Debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-outputs
          path: app/build/outputs/**

      # محاولة تجهيز keystore للتوقيع الرسمي إذا كان موجود
      - name: Prepare signing keystore (if provided)
        run: |
          if [ -n "${SIGNING_STORE_FILE_B64}" ] && [ -n "${SIGNING_STORE_PASSWORD}" ] && \
             [ -n "${SIGNING_KEY_ALIAS}" ] && [ -n "${SIGNING_KEY_PASSWORD}" ]; then
            mkdir -p app/signing
            echo "${SIGNING_STORE_FILE_B64}" | base64 -d > app/signing/release.jks
            echo "Custom signing keystore prepared."
          else
            echo "No signing secrets found. Will use debug signing."
          fi
        env:
          SIGNING_STORE_FILE_B64: ${{ secrets.SIGNING_STORE_FILE_B64 }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      # بناء نسخة Release موقعة أو debug-signed
      - name: Build Release
        run: |
          if [ -n "${SIGNING_STORE_FILE_B64}" ] && [ -n "${SIGNING_STORE_PASSWORD}" ] && \
             [ -n "${SIGNING_KEY_ALIAS}" ] && [ -n "${SIGNING_KEY_PASSWORD}" ]; then
            ./gradlew :app:assembleRelease --no-daemon --stacktrace
          else
            echo "No signing config provided. Building unsigned release (will be debug-signed)."
            ./gradlew :app:assembleRelease --no-daemon --stacktrace
          fi
        env:
          SIGNING_STORE_FILE_B64: ${{ secrets.SIGNING_STORE_FILE_B64 }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Upload Release artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-release-outputs
          path: app/build/outputs/**

      - name: Collect APKs into repo artifacts directory (main branch only)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          rm -rf artifacts && mkdir -p artifacts/debug artifacts/release || true
          cp -vr app/build/outputs/apk/debug/*.apk artifacts/debug/ 2>/dev/null || true
          cp -vr app/build/outputs/apk/release/*.apk artifacts/release/ 2>/dev/null || true
        shell: bash

      - name: Commit APKs into repository (main branch only)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(build): add generated APKs to artifacts/"
          branch: main
          file_pattern: artifacts/**
