name: Build Winlator with Wine & Box86

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. سحب الكود مع الـ Submodules
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2. تثبيت JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      # 3. تثبيت Android SDK
      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # 4. تثبيت NDK و CMake
      - name: Install NDK
        run: sdkmanager --install "ndk;23.1.7779620" "cmake;3.22.1"

      # 5. تثبيت أدوات البناء الإضافية (لـ Wine و Box86)
      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake ninja-build pkg-config python3-mako python3-setuptools git

      # 6. بناء Box86/Box64
      - name: Build Box86
        run: |
          git clone https://github.com/ptitSeb/box86.git
          mkdir box86/build && cd box86/build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DARM_DYNAREC=ON
          make -j$(nproc)
          cd ../..

      - name: Build Box64
        run: |
          git clone https://github.com/ptitSeb/box64.git
          mkdir box64/build && cd box64/build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DARM_DYNAREC=ON
          make -j$(nproc)
          cd ../..

      # 7. (اختياري) بناء Wine
      # ملاحظة: بناء Wine على GitHub Actions معقد وطويل، وأحياناً يستهلك وقت أكثر من المسموح.
      # في الغالب ستستخدم ملفات Wine جاهزة وتنسخها إلى المشروع.

      # 8. إعطاء صلاحية تشغيل Gradlew
      - name: Grant permission
        run: chmod +x gradlew

      # 9. بناء APK
      - name: Build APK
        run: ./gradlew assembleDebug

      # 10. رفع الـ APK كـ Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: winlator-apk
          path: app/build/outputs/apk/debug/app-debug.apk
