name: Build Winlator APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # 4. Set up CMake
      - name: Set up CMake
        run: sdkmanager "cmake;3.22.1"

      # 5. Set up NDK
      - name: Set up NDK
        run: sdkmanager "ndk;22.1.7171670"

      # 6. Install Gradle
      - name: Install Gradle
        uses: gradle/gradle-build-action@v3

      # 7. Build Debug APK inside app/
      - name: Build Debug APK
        working-directory: ./app
        run: gradle assembleDebug

      # 8. Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Winlator-debug
          path: app/build/outputs/apk/debug/app-debug.apk